name: Build pages
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
        access-token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install doxygen python3
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions mkdocs-macros-plugin mkdocs-redirects mkdoxy
        
    - name: Clone repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'RedPepperDec'
        repository: 'RedPepperWiki'
        branch: 'master'
        persist-credentials: false
        access-token: ${{ secrets.GH_TOKEN }}
        
    - name: Convert Charset
      run: |
        SEARCH_DIRS="lib Game"
        EXTENSIONS="*.cpp *.c *.hpp *.h"
        TO_ENCODING="UTF-8"
        
        for DIR in $SEARCH_DIRS; do
          for EXT in $EXTENSIONS; do
            find "$DIR" -type f -name "$EXT" -print0 | while IFS= read -r -d $'\0' FILE; do
              iconv -f SHIFT_JIS -t "$TO_ENCODING" -c "$FILE" > "$FILE.tmp" 2>/dev/null
              
              if [ $? -eq 0 ] && [ -s "$FILE.tmp" ]; then
                echo "OK iconv $FILE"
                sed -i 's/¥/\\/g; s/‾/~/g' "$FILE.tmp"
                mv "$FILE.tmp" "$FILE"
              else
                echo "Failed to iconv $FILE"
                rm -f "$FILE.tmp"
              fi
            done
          done
        done
    - name: Build and Deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        mkdir priv
        mv RedPepperWiki priv/RedPepperWiki
        python -m mkdocs build --config-file priv/RedPepperWiki/mkdocs.yml
        # upload
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/RedPepperDec/RedPepper.git
        echo "prp.moddi.dev" >> priv/RedPepperWiki/site/CNAME
        echo "Set CNAME"
        python -m ghp_import -n -f -p -b website priv/RedPepperWiki/site

